# coding: UTF-8
dog_dict = {
    'Affenpinscher': '猴犬',
    'Afghan hound': '阿富汗猎犬',
    'Airedale terrier': '㹴犬',
    'Akita': '秋田犬',
    'Alaskan malamute': '阿拉斯加雪橇犬',
    'American eskimo dog': '玩具美国爱斯基摩犬',
    'American foxhound': '美国猎狐犬',
    'American staffordshire terrier': '美国斯塔福梗',
    'American water spaniel': '枪猎犬',
    'Anatolian shepherd dog': '安纳托利亚牧羊犬',
    'Australian cattle dog': '澳洲牧牛犬',
    'Australian shepherd': '澳大利亚牧羊犬',
    'Australian terrier': '澳大利亚梗',
    'Basenji': '巴仙吉犬',
    'Basset hound': '巴吉度猎犬',
    'Beagle': '比格猎犬',
    'Bearded collie': '长须柯利牧羊犬',
    'Beauceron': '法国牧羊犬',
    'Bedlington terrier': '贝灵顿梗犬',
    'Belgian malinois': '比利时牧羊犬',
    'Belgian sheepdog': '比利时牧羊犬',
    'Belgian tervuren': '比利时特伏丹犬',
    'Bernese mountain dog': '伯恩山犬',
    'Bichon frise': '卷毛比雄犬',
    'Black and tan coonhound': '黑褐猎浣熊犬',
    'Black russian terrier': '黑俄罗斯梗犬',
    'Bloodhound': '寻血猎犬',
    'Bluetick coonhound': '布鲁泰克猎浣熊犬',
    'Border collie': '边境牧羊犬',
    'Border terrier': '伯德梗',
    'Borzoi': '俄罗斯猎狼犬',
    'Boston terrier': '波士顿梗犬',
    'Bouvier des flandres': '波兰德斯布比野犬',
    'Boxer': "拳师犬",
    'Boykin spaniel': '博伊金猎犬',
    'Briard': '布里犬',
    'Brittany': '布列塔尼犬',
    'Brussels griffon': '布鲁塞尔粗毛猎犬',
    'Bull terrier': '牛头梗',
    'Bulldog': '斗牛犬',
    'Bullmastiff': '斗牛獒',
    'Cairn terrier': '凯恩梗',
    'Canaan dog': '迦南犬',
    'Cane corso': '意大利卡斯罗',
    'Cardigan welsh corgi': '卡迪根威尔士柯基犬',
    'Cavalier king charles spaniel': '骑士查理王小猎犬',
    'Chesapeake bay retriever': '切萨皮克海湾寻回犬',
    'Chihuahua': '奇瓦瓦州',
    'Chinese crested': '中国冠毛犬',
    'Chinese shar-pei': '中国沙皮犬',
    'Chow chow': '松狮犬',
    'Clumber spaniel': '西班牙小猎犬',
    'Cocker spaniel': '英国可卡犬',
    'Collie': '边境牧羊犬',
    'Curly-coated retriever': '卷毛寻回犬',
    'Dachshund': '腊肠犬',
    'Dalmatian': '达尔马提犬',
    'Dandie dinmont terrier': '短脚长身梗犬',
    'Doberman pinscher': '杜宾犬',
    'Dogue de bordeaux': '波尔多犬',
    'English cocker spaniel': '英国可卡犬',
    'English setter': '英格兰雪达犬',
    'English springer spaniel': '史宾格',
    'English toy spaniel': '英国玩具犬',
    'Entlebucher mountain dog': '山地犬',
    'Field spaniel': '田野小猎犬',
    'Finnish spitz': '芬兰波美拉尼亚丝毛狗',
    'Flat-coated retriever': '弗莱特寻回犬',
    'French bulldog': '法国斗牛犬',
    'German pinscher': '德国宾莎犬',
    'German shepherd dog': '德国牧羊犬',
    'German shorthaired pointer': '德国短毛指示猎犬',
    'German wirehaired pointer': '德国硬毛波音达',
    'Giant schnauzer': '巨型雪纳瑞犬',
    'Glen of imaal terrier': '爱尔兰峡谷梗犬',
    'Golden retriever': '金毛寻回犬',
    'Gordon setter': '塞特猎犬',
    'Great dane': '大丹犬',
    'Great pyrenees': '大白熊犬',
    'Greater swiss mountain dog': '大瑞士山地犬',
    'Greyhound': '格雷伊猎犬',
    'Havanese': '哈瓦那犬',
    'Ibizan hound': '伊维萨猎犬',
    'Icelandic sheepdog': '冰岛牧羊犬',
    'Irish red and white setter': '爱尔兰红白雪达犬',
    'Irish setter': '爱尔兰雪达犬',
    'Irish terrier': '爱尔兰梗',
    'Irish water spaniel': ' 爱尔兰水猎犬',
    'Irish wolfhound': '爱尔兰猎狼犬',
    'Italian greyhound': '意大利灰狗',
    'Japanese chin': '日本狆',
    'Keeshond': '荷兰毛狮犬',
    'Kerry blue terrier': '凯利蓝梗',
    'Komondor': '可蒙犬',
    'Kuvasz': ' 库瓦兹犬',
    'Labrador retriever': '拉布拉多猎犬',
    'Lakeland terrier': '湖畔梗',
    'Leonberger': '兰波格犬',
    'Lhasa apso': '拉萨犬',
    'Lowchen': '罗秦犬',
    'Maltese': '马尔济斯犬',
    'Manchester terrier': '玩具曼彻斯特犬',
    'Mastiff': '马士提夫獒犬',
    'Miniature schnauzer': '迷你雪瑞纳',
    'Neapolitan mastiff': '那不勒斯獒',
    'Newfoundland': '纽芬兰犬',
    'Norfolk terrier': '诺福克梗',
    'Norwegian buhund': '挪威布哈德犬',
    'Norwegian elkhound': '挪威猎鹿犬',
    'Norwegian lundehund': '挪威伦德猎犬',
    'Norwich terrier': '挪威梗',
    'Nova scotia duck tolling retriever': '新斯科舍猎鸭寻猎犬',
    'Old english sheepdog': '英国古代牧羊犬',
    'Otterhound': '猎水獭犬',
    'Papillon': '蝴蝶犬',
    'Parson russell terrier': '牧师罗素梗犬',
    'Pekingese': '北京犬',
    'Pembroke welsh corgi': '彭布罗克威尔士柯基犬',
    'Petit basset griffon vendeen': '贝吉格里芬凡丁犬',
    'Pharaoh hound': '法老王猎犬',
    'Plott': '普罗特猎犬',
    'Pointer': '指示犬',
    'Pomeranian': '博美犬',
    'Poodle': 'Poodle贵宾犬',
    'Portuguese water dog': '葡萄牙水犬',
    'Saint bernard': '圣伯纳犬',
    'Silky terrier': '丝毛梗犬',
    'Smooth fox terrier': '短毛猎狐梗',
    'Tibetan mastiff': '藏獒',
    'Welsh springer spaniel': '威尔士跳猎犬',
    'Wirehaired pointing griffon': '硬毛指示格里芬犬',
    'Xoloitzcuintli': '墨西哥无毛犬',
    'Yorkshire terrier': '约克夏梗犬'}
